# Generated by Django 5.1 on 2024-10-01 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_compra_itenscompra_delete_manga"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manhwa",
            options={"ordering": ["numero"]},
        ),
        migrations.AddField(
            model_name="manhwa",
            name="data_publicacao",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manhwa",
            name="documento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capitulos",
                to="uploader.document",
            ),
        ),
        migrations.AddField(
            model_name="manhwa",
            name="idioma",
            field=models.CharField(
                choices=[("PT", "Português"), ("EN", "Inglês"), ("ES", "Espanhol"), ("JP", "Japonês")],
                default="PT",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="manhwa",
            name="numero",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="manhwa",
            name="capa",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="uploader.image"
            ),
        ),
        migrations.AlterField(
            model_name="manhwa",
            name="titulo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="manhwa",
            unique_together={("numero", "titulo")},
        ),
    ]
