# Generated by Django 5.1.3 on 2024-12-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_user_tipo_usuario_alter_user_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passage_id",
        ),
    ]
