# Generated by Django 5.1.3 on 2024-12-17 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_avaliacaomahhwa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacaomahhwa",
            name="puntuacao",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
