# Generated by Django 5.1.3 on 2024-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_user_passage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passage_id",
            field=models.CharField(default=50, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
