# Generated by Django 5.1.3 on 2024-12-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_avaliacaomahhwa_puntuacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capitulo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("numero", models.IntegerField()),
                (
                    "manhwa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="capitulos", to="core.manhwa"
                    ),
                ),
            ],
        ),
    ]
